### ISSUE TITLE
vertx-addon won't install

### ISSUE THREAD

**Issue by rdruss** [forge/vertx-addon#2]
[io.vertx.book.message.faulty]$ addon-install --coordinate org.jboss.forge.addon:vertx      
***ERROR*** Error while executing 'addon-install'
***INFO*** (type "export VERBOSE=true" to enable stack traces)
***ERROR*** No Artifact version found for org.jboss.forge.addon:vertx

Using Forge 3.7.0 installed with homebrew and Java 8

**Comment by gastaldi** [comment]
Try `addon-install-from-catalog`, otherwise you need to specify the version you want.

**Comment by rdruss** [comment]
Ah, that worked.  Thanks, @gastaldi
